/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRootPane;
import javax.swing.JTextField;

/**
 *
 * @author rajasharma
 */
public class CoachNotesForPlayer extends javax.swing.JFrame {

    /**
     * Creates new form CoachNotesForPlayer
     */
    public CoachNotesForPlayer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player7Label = new javax.swing.JLabel();
        player8Label = new javax.swing.JLabel();
        player9Label = new javax.swing.JLabel();
        player10Label = new javax.swing.JLabel();
        updateAll = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        p1FirstTextField = new javax.swing.JTextField();
        p2FirstTextField = new javax.swing.JTextField();
        p3FirstTextField = new javax.swing.JTextField();
        p4FirstTextField = new javax.swing.JTextField();
        p5FirstTextField = new javax.swing.JTextField();
        p6FirstTextField = new javax.swing.JTextField();
        p8FirstTextField = new javax.swing.JTextField();
        p7FirstTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        player1Label = new javax.swing.JLabel();
        player2Label = new javax.swing.JLabel();
        p9FirstTextField = new javax.swing.JTextField();
        p10FirstTextField = new javax.swing.JTextField();
        player3Label = new javax.swing.JLabel();
        player4Label = new javax.swing.JLabel();
        player5Label = new javax.swing.JLabel();
        player6Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        player7Label.setText("Player7");

        player8Label.setText("Player8");

        player9Label.setText("Player9");

        player10Label.setText("Player10");

        updateAll.setText("Update All");

        jLabel4.setText("Notes to Player");

        p2FirstTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2FirstTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Player");

        player1Label.setText("Player1");

        player2Label.setText("Player2");

        player3Label.setText("Player3");

        player4Label.setText("Player4");

        player5Label.setText("Player5");

        player6Label.setText("Player6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(player3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(player2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(player5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(player4Label))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p7FirstTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                    .addComponent(p4FirstTextField)
                                    .addComponent(p3FirstTextField)
                                    .addComponent(p2FirstTextField)
                                    .addComponent(p1FirstTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(player10Label, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(player9Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(player8Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(player7Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(player6Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(p10FirstTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                    .addComponent(p9FirstTextField)
                                    .addComponent(p8FirstTextField)
                                    .addComponent(p6FirstTextField)
                                    .addComponent(p5FirstTextField)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(updateAll)))
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(player1Label)
                        .addComponent(jLabel1))
                    .addGap(37, 37, 37)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(p1FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p7FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p5FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p6FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p8FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p9FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player9Label, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p10FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player10Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateAll)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4))
                    .addGap(18, 18, 18)
                    .addComponent(player1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(363, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p2FirstTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2FirstTextFieldActionPerformed
     
    }//GEN-LAST:event_p2FirstTextFieldActionPerformed

    public JButton getjButton1() {
        return updateAll;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JTextField getP10FirstTextField() {
        return p10FirstTextField;
    }

    public JTextField getP1FirstTextField() {
        return p1FirstTextField;
    }

    public JTextField getP2FirstTextField() {
        return p2FirstTextField;
    }

    public JTextField getP3FirstTextField() {
        return p3FirstTextField;
    }

    public JTextField getP4FirstTextField() {
        return p4FirstTextField;
    }

    public JTextField getP5FirstTextField() {
        return p5FirstTextField;
    }

    public JTextField getP6FirstTextField() {
        return p6FirstTextField;
    }

    public JTextField getP7FirstTextField() {
        return p7FirstTextField;
    }

    public JTextField getP8FirstTextField() {
        return p8FirstTextField;
    }

    public JTextField getP9FirstTextField() {
        return p9FirstTextField;
    }

    public JLabel getPlayer10Label() {
        return player10Label;
    }

    public JLabel getPlayer1Label() {
        return player1Label;
    }

    public JLabel getPlayer2Label() {
        return player2Label;
    }

    public JLabel getPlayer3Label() {
        return player3Label;
    }

    public JLabel getPlayer4Label() {
        return player4Label;
    }

    public JLabel getPlayer5Label() {
        return player5Label;
    }

    public JLabel getPlayer6Label() {
        return player6Label;
    }

    public JLabel getPlayer7Label() {
        return player7Label;
    }

    public JLabel getPlayer8Label() {
        return player8Label;
    }

    public JLabel getPlayer9Label() {
        return player9Label;
    }

    

    public JButton getUpdateAll() {
        return updateAll;
    }

    /**
     * @param args the command line arguments
     */
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField p10FirstTextField;
    private javax.swing.JTextField p1FirstTextField;
    private javax.swing.JTextField p2FirstTextField;
    private javax.swing.JTextField p3FirstTextField;
    private javax.swing.JTextField p4FirstTextField;
    private javax.swing.JTextField p5FirstTextField;
    private javax.swing.JTextField p6FirstTextField;
    private javax.swing.JTextField p7FirstTextField;
    private javax.swing.JTextField p8FirstTextField;
    private javax.swing.JTextField p9FirstTextField;
    private javax.swing.JLabel player10Label;
    private javax.swing.JLabel player1Label;
    private javax.swing.JLabel player2Label;
    private javax.swing.JLabel player3Label;
    private javax.swing.JLabel player4Label;
    private javax.swing.JLabel player5Label;
    private javax.swing.JLabel player6Label;
    private javax.swing.JLabel player7Label;
    private javax.swing.JLabel player8Label;
    private javax.swing.JLabel player9Label;
    private javax.swing.JButton updateAll;
    // End of variables declaration//GEN-END:variables

    
}
