/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author rajasharma
 */
public class CoachRecentGame extends javax.swing.JFrame {

    /**
     * Creates new form CoachRecentGame
     */
    public CoachRecentGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextField43 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        p1TotalLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        player1Label = new javax.swing.JLabel();
        player2Label = new javax.swing.JLabel();
        player3Label = new javax.swing.JLabel();
        player4Label = new javax.swing.JLabel();
        player5Label = new javax.swing.JLabel();
        player6Label = new javax.swing.JLabel();
        player7Label = new javax.swing.JLabel();
        player8Label = new javax.swing.JLabel();
        player9Label = new javax.swing.JLabel();
        player10Label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        player1NumberTextField = new javax.swing.JTextField();
        player2NumberTextField = new javax.swing.JTextField();
        player3NumberTextField = new javax.swing.JTextField();
        player4NumberTextField = new javax.swing.JTextField();
        player5NumberTextField = new javax.swing.JTextField();
        player6NumberTextField = new javax.swing.JTextField();
        player8NumberTextField = new javax.swing.JTextField();
        player7NumberTextField = new javax.swing.JTextField();
        player9NumberTextField = new javax.swing.JTextField();
        player10NumberTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        p2FoulComboBox = new javax.swing.JComboBox<>();
        p1FoulComboBox = new javax.swing.JComboBox<>();
        p3FoulComboBox = new javax.swing.JComboBox<>();
        p4FoulComboBox = new javax.swing.JComboBox<>();
        p5FoulComboBox = new javax.swing.JComboBox<>();
        p6FoulComboBox = new javax.swing.JComboBox<>();
        p8FoulComboBox = new javax.swing.JComboBox<>();
        p7FoulComboBox = new javax.swing.JComboBox<>();
        p9FoulComboBox = new javax.swing.JComboBox<>();
        p10FoulComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        p1FirstTextField = new javax.swing.JTextField();
        p2FirstTextField = new javax.swing.JTextField();
        p3FirstTextField = new javax.swing.JTextField();
        p4FirstTextField = new javax.swing.JTextField();
        p5FirstTextField = new javax.swing.JTextField();
        p6FirstTextField = new javax.swing.JTextField();
        p8FirstTextField = new javax.swing.JTextField();
        p7FirstTextField = new javax.swing.JTextField();
        p9FirstTextField = new javax.swing.JTextField();
        p10FirstTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        p10ForthTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        p1ForthTextField = new javax.swing.JTextField();
        p2ForthTextField = new javax.swing.JTextField();
        p3ForthTextField = new javax.swing.JTextField();
        p4ForthTextField = new javax.swing.JTextField();
        p5ForthTextField = new javax.swing.JTextField();
        p6ForthTextField = new javax.swing.JTextField();
        p8ForthTextField = new javax.swing.JTextField();
        p7ForthTextField = new javax.swing.JTextField();
        p9ForthTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        p2TotalLabel = new javax.swing.JLabel();
        p3TotalLabel = new javax.swing.JLabel();
        p4TotalLabel = new javax.swing.JLabel();
        p5TotalLabel = new javax.swing.JLabel();
        p6TotalLabel = new javax.swing.JLabel();
        p10TotalLabel = new javax.swing.JLabel();
        p7TotalLabel = new javax.swing.JLabel();
        p8TotalLabel = new javax.swing.JLabel();
        p9TotalLabel = new javax.swing.JLabel();
        p1SecondTextField = new javax.swing.JTextField();
        p2SecondTextField = new javax.swing.JTextField();
        p3SecondTextField = new javax.swing.JTextField();
        p4SecondTextField = new javax.swing.JTextField();
        p5SecondTextField = new javax.swing.JTextField();
        p6SecondTextField = new javax.swing.JTextField();
        p8SecondTextField = new javax.swing.JTextField();
        p7SecondTextField = new javax.swing.JTextField();
        p9SecondTextField = new javax.swing.JTextField();
        p10SecondTextField = new javax.swing.JTextField();
        p1ThirdTextField = new javax.swing.JTextField();
        p2ThirdTextField = new javax.swing.JTextField();
        p3ThirdTextField = new javax.swing.JTextField();
        p4ThirdTextField = new javax.swing.JTextField();
        p5ThirdTextField = new javax.swing.JTextField();
        p6ThirdTextField = new javax.swing.JTextField();
        p8ThirdTextField = new javax.swing.JTextField();
        p7ThirdTextField = new javax.swing.JTextField();
        p9ThirdTextField = new javax.swing.JTextField();
        p10ThirdTextField = new javax.swing.JTextField();
        p1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel7.setText("2nd Quarter");

        jTextField43.setText("jTextField1");

        jTextField50.setText("jTextField1");

        jTextField47.setText("jTextField1");

        jTextField49.setText("jTextField1");

        jTextField48.setText("jTextField1");

        jTextField45.setText("jTextField1");

        jTextField46.setText("jTextField1");

        jTextField41.setText("jTextField1");

        jTextField42.setText("jTextField1");

        jTextField44.setText("jTextField1");

        p1TotalLabel.setText("player 1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Player");

        player1Label.setText("Player1");

        player2Label.setText("Player2");

        player3Label.setText("Player3");

        player4Label.setText("Player4");

        player5Label.setText("Player5");

        player6Label.setText("Player6");

        player7Label.setText("Player7");

        player8Label.setText("Player8");

        player9Label.setText("Player9");

        player10Label.setText("Player10");

        jLabel2.setText("#");

        player2NumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2NumberTextFieldActionPerformed(evt);
            }
        });

        player3NumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player3NumberTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Fouls");

        p2FoulComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6" }));

        p1FoulComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6" }));

        p3FoulComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6" }));

        p4FoulComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6" }));

        p5FoulComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6" }));

        p6FoulComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6" }));

        p8FoulComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6" }));

        p7FoulComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6" }));

        p9FoulComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6" }));

        p10FoulComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6" }));

        jLabel4.setText("1st Quarter");

        jLabel5.setText("2nd Quarter");

        p2FirstTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2FirstTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("3rd Quarter");

        jLabel8.setText("4th Quarter");

        jLabel9.setText("Total Sum");

        p2TotalLabel.setText("player 2");

        p3TotalLabel.setText("player 3");

        p4TotalLabel.setText("player 4");

        p5TotalLabel.setText("player 5");

        p6TotalLabel.setText("player 6");

        p10TotalLabel.setText("player 10");

        p7TotalLabel.setText("player 7");

        p8TotalLabel.setText("player 8");

        p9TotalLabel.setText("player 9");

        p4SecondTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4SecondTextFieldActionPerformed(evt);
            }
        });

        p10SecondTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p10SecondTextFieldActionPerformed(evt);
            }
        });

        p1.setText("player 1");

        jButton1.setText("Enter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(player10Label, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(player9Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player8Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player7Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player6Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player5Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player4Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(player7NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p7FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p7FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(player1NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(player2NumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(player3NumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(player4NumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(player5NumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(player6NumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(player8NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(player9NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(player10NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p1FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p2FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p3FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p4FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p5FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p6FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p9FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p8FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p10FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(p2FirstTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                .addComponent(p3FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(p4FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(p5FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(p6FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(p8FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(p9FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(p1FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(p10FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(p2SecondTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addComponent(p1SecondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(p10SecondTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addComponent(p9SecondTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p8SecondTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p7SecondTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p6SecondTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p5SecondTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p4SecondTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p3SecondTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(p7ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p3ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(p4ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(p5ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(p6ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(p8ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(p9ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(p1ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(p10ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p2ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(p6ForthTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p5ForthTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p4ForthTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p3ForthTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p2ForthTextField)
                                    .addComponent(p7ForthTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p8ForthTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p9ForthTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p10ForthTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(p1ForthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p2TotalLabel)
                            .addComponent(p4TotalLabel)
                            .addComponent(p5TotalLabel)
                            .addComponent(p6TotalLabel)
                            .addComponent(p7TotalLabel)
                            .addComponent(p8TotalLabel)
                            .addComponent(p9TotalLabel)
                            .addComponent(p10TotalLabel)
                            .addComponent(p3TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p1))))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(278, 278, 278))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(player1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(player1NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p1FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(player2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(player2NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p2FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(player3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(player3NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p3FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p3FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(player4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(player4NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p4FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p4FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p4SecondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(p2ForthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p2TotalLabel))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(player5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(player5NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p5FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p5FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p5SecondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p5ForthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p5TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p4ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(player6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(player6NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p6FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p6FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p6SecondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p6ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p6ForthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p6TotalLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(player7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(player7NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(p7FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(p7FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(p7SecondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(p7ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(p7ForthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(p7TotalLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(player8NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p8FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p8FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p8SecondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p8ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p8ForthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p8TotalLabel)
                                    .addComponent(player8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(player9Label, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(player9NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p9FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p9FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p9SecondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p9ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p9ForthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p9TotalLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(player10Label)
                                    .addComponent(player10NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p10FoulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p10FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p10SecondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p10ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p10ForthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p10TotalLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(p1FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(p2SecondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(p2FirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(p2ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(p1SecondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(p3SecondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p3ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p3ForthTextField)
                                    .addComponent(p3TotalLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(p5ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p4ForthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p4TotalLabel))
                                .addGap(19, 19, 19))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(p1ThirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p1ForthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p1)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jButton1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjButton1() {
        return jButton1;
    }

    private void player2NumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2NumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player2NumberTextFieldActionPerformed

    private void player3NumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player3NumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player3NumberTextFieldActionPerformed

    private void p2FirstTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2FirstTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2FirstTextFieldActionPerformed

    private void p4SecondTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4SecondTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p4SecondTextFieldActionPerformed

    private void p10SecondTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p10SecondTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p10SecondTextFieldActionPerformed

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public JTextField getjTextField41() {
        return jTextField41;
    }

    public JTextField getjTextField42() {
        return jTextField42;
    }

    public JTextField getjTextField43() {
        return jTextField43;
    }

    public JTextField getjTextField44() {
        return jTextField44;
    }

    public JTextField getjTextField45() {
        return jTextField45;
    }

    public JTextField getjTextField46() {
        return jTextField46;
    }

    public JTextField getjTextField47() {
        return jTextField47;
    }

    public JTextField getjTextField48() {
        return jTextField48;
    }

    public JTextField getjTextField49() {
        return jTextField49;
    }

    public JTextField getjTextField50() {
        return jTextField50;
    }

    public JLabel getP1() {
        return p1;
    }

    public JTextField getP10FirstTextField() {
        return p10FirstTextField;
    }

    public JTextField getP10ForthTextField() {
        return p10ForthTextField;
    }

    public JComboBox<String> getP10FoulComboBox() {
        return p10FoulComboBox;
    }

    public JTextField getP10SecondTextField() {
        return p10SecondTextField;
    }

    public JTextField getP10ThirdTextField() {
        return p10ThirdTextField;
    }

    public JLabel getP10TotalLabel() {
        return p10TotalLabel;
    }

    public JTextField getP1FirstTextField() {
        return p1FirstTextField;
    }

    public JTextField getP1ForthTextField() {
        return p1ForthTextField;
    }

    public JComboBox<String> getP1FoulComboBox() {
        return p1FoulComboBox;
    }

    public JTextField getP1SecondTextField() {
        return p1SecondTextField;
    }

    public JTextField getP1ThirdTextField() {
        return p1ThirdTextField;
    }

    public JLabel getP1TotalLabel() {
        return p1TotalLabel;
    }

    public JTextField getP2FirstTextField() {
        return p2FirstTextField;
    }

    public JTextField getP2ForthTextField() {
        return p2ForthTextField;
    }

    public JComboBox<String> getP2FoulComboBox() {
        return p2FoulComboBox;
    }

    public JTextField getP2SecondTextField() {
        return p2SecondTextField;
    }

    public JTextField getP2ThirdTextField() {
        return p2ThirdTextField;
    }

    public JLabel getP2TotalLabel() {
        return p2TotalLabel;
    }

    public JTextField getP3FirstTextField() {
        return p3FirstTextField;
    }

    public JTextField getP3ForthTextField() {
        return p3ForthTextField;
    }

    public JComboBox<String> getP3FoulComboBox() {
        return p3FoulComboBox;
    }

    public JTextField getP3SecondTextField() {
        return p3SecondTextField;
    }

    public JTextField getP3ThirdTextField() {
        return p3ThirdTextField;
    }

    public JLabel getP3TotalLabel() {
        return p3TotalLabel;
    }

    public JTextField getP4FirstTextField() {
        return p4FirstTextField;
    }

    public JTextField getP4ForthTextField() {
        return p4ForthTextField;
    }

    public JComboBox<String> getP4FoulComboBox() {
        return p4FoulComboBox;
    }

    public JTextField getP4SecondTextField() {
        return p4SecondTextField;
    }

    public JTextField getP4ThirdTextField() {
        return p4ThirdTextField;
    }

    public JLabel getP4TotalLabel() {
        return p4TotalLabel;
    }

    public JTextField getP5FirstTextField() {
        return p5FirstTextField;
    }

    public JTextField getP5ForthTextField() {
        return p5ForthTextField;
    }

    public JComboBox<String> getP5FoulComboBox() {
        return p5FoulComboBox;
    }

    public JTextField getP5SecondTextField() {
        return p5SecondTextField;
    }

    public JTextField getP5ThirdTextField() {
        return p5ThirdTextField;
    }

    public JLabel getP5TotalLabel() {
        return p5TotalLabel;
    }

    public JTextField getP6FirstTextField() {
        return p6FirstTextField;
    }

    public JTextField getP6ForthTextField() {
        return p6ForthTextField;
    }

    public JComboBox<String> getP6FoulComboBox() {
        return p6FoulComboBox;
    }

    public JTextField getP6SecondTextField() {
        return p6SecondTextField;
    }

    public JTextField getP6ThirdTextField() {
        return p6ThirdTextField;
    }

    public JLabel getP6TotalLabel() {
        return p6TotalLabel;
    }

    public JTextField getP7FirstTextField() {
        return p7FirstTextField;
    }

    public JTextField getP7ForthTextField() {
        return p7ForthTextField;
    }

    public JComboBox<String> getP7FoulComboBox() {
        return p7FoulComboBox;
    }

    public JTextField getP7SecondTextField() {
        return p7SecondTextField;
    }

    public JTextField getP7ThirdTextField() {
        return p7ThirdTextField;
    }

    public JLabel getP7TotalLabel() {
        return p7TotalLabel;
    }

    public JTextField getP8FirstTextField() {
        return p8FirstTextField;
    }

    public JTextField getP8ForthTextField() {
        return p8ForthTextField;
    }

    public JComboBox<String> getP8FoulComboBox() {
        return p8FoulComboBox;
    }

    public JTextField getP8SecondTextField() {
        return p8SecondTextField;
    }

    public JTextField getP8ThirdTextField() {
        return p8ThirdTextField;
    }

    public JLabel getP8TotalLabel() {
        return p8TotalLabel;
    }

    public JTextField getP9FirstTextField() {
        return p9FirstTextField;
    }

    public JTextField getP9ForthTextField() {
        return p9ForthTextField;
    }

    public JComboBox<String> getP9FoulComboBox() {
        return p9FoulComboBox;
    }

    public JTextField getP9SecondTextField() {
        return p9SecondTextField;
    }

    public JTextField getP9ThirdTextField() {
        return p9ThirdTextField;
    }

    public JLabel getP9TotalLabel() {
        return p9TotalLabel;
    }

    public JLabel getPlayer10Label() {
        return player10Label;
    }

    public JTextField getPlayer10NumberTextField() {
        return player10NumberTextField;
    }

    public JLabel getPlayer1Label() {
        return player1Label;
    }

    public JTextField getPlayer1NumberTextField() {
        return player1NumberTextField;
    }

    public JLabel getPlayer2Label() {
        return player2Label;
    }

    public JTextField getPlayer2NumberTextField() {
        return player2NumberTextField;
    }

    public JLabel getPlayer3Label() {
        return player3Label;
    }

    public JTextField getPlayer3NumberTextField() {
        return player3NumberTextField;
    }

    public JLabel getPlayer4Label() {
        return player4Label;
    }

    public JTextField getPlayer4NumberTextField() {
        return player4NumberTextField;
    }

    public JLabel getPlayer5Label() {
        return player5Label;
    }

    public JTextField getPlayer5NumberTextField() {
        return player5NumberTextField;
    }

    public JLabel getPlayer6Label() {
        return player6Label;
    }

    public JTextField getPlayer6NumberTextField() {
        return player6NumberTextField;
    }

    public JLabel getPlayer7Label() {
        return player7Label;
    }

    public JTextField getPlayer7NumberTextField() {
        return player7NumberTextField;
    }

    public JLabel getPlayer8Label() {
        return player8Label;
    }

    public JTextField getPlayer8NumberTextField() {
        return player8NumberTextField;
    }

    public JLabel getPlayer9Label() {
        return player9Label;
    }

    public JTextField getPlayer9NumberTextField() {
        return player9NumberTextField;
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JLabel p1;
    private javax.swing.JTextField p10FirstTextField;
    private javax.swing.JTextField p10ForthTextField;
    private javax.swing.JComboBox<String> p10FoulComboBox;
    private javax.swing.JTextField p10SecondTextField;
    private javax.swing.JTextField p10ThirdTextField;
    private javax.swing.JLabel p10TotalLabel;
    private javax.swing.JTextField p1FirstTextField;
    private javax.swing.JTextField p1ForthTextField;
    private javax.swing.JComboBox<String> p1FoulComboBox;
    private javax.swing.JTextField p1SecondTextField;
    private javax.swing.JTextField p1ThirdTextField;
    private javax.swing.JLabel p1TotalLabel;
    private javax.swing.JTextField p2FirstTextField;
    private javax.swing.JTextField p2ForthTextField;
    private javax.swing.JComboBox<String> p2FoulComboBox;
    private javax.swing.JTextField p2SecondTextField;
    private javax.swing.JTextField p2ThirdTextField;
    private javax.swing.JLabel p2TotalLabel;
    private javax.swing.JTextField p3FirstTextField;
    private javax.swing.JTextField p3ForthTextField;
    private javax.swing.JComboBox<String> p3FoulComboBox;
    private javax.swing.JTextField p3SecondTextField;
    private javax.swing.JTextField p3ThirdTextField;
    private javax.swing.JLabel p3TotalLabel;
    private javax.swing.JTextField p4FirstTextField;
    private javax.swing.JTextField p4ForthTextField;
    private javax.swing.JComboBox<String> p4FoulComboBox;
    private javax.swing.JTextField p4SecondTextField;
    private javax.swing.JTextField p4ThirdTextField;
    private javax.swing.JLabel p4TotalLabel;
    private javax.swing.JTextField p5FirstTextField;
    private javax.swing.JTextField p5ForthTextField;
    private javax.swing.JComboBox<String> p5FoulComboBox;
    private javax.swing.JTextField p5SecondTextField;
    private javax.swing.JTextField p5ThirdTextField;
    private javax.swing.JLabel p5TotalLabel;
    private javax.swing.JTextField p6FirstTextField;
    private javax.swing.JTextField p6ForthTextField;
    private javax.swing.JComboBox<String> p6FoulComboBox;
    private javax.swing.JTextField p6SecondTextField;
    private javax.swing.JTextField p6ThirdTextField;
    private javax.swing.JLabel p6TotalLabel;
    private javax.swing.JTextField p7FirstTextField;
    private javax.swing.JTextField p7ForthTextField;
    private javax.swing.JComboBox<String> p7FoulComboBox;
    private javax.swing.JTextField p7SecondTextField;
    private javax.swing.JTextField p7ThirdTextField;
    private javax.swing.JLabel p7TotalLabel;
    private javax.swing.JTextField p8FirstTextField;
    private javax.swing.JTextField p8ForthTextField;
    private javax.swing.JComboBox<String> p8FoulComboBox;
    private javax.swing.JTextField p8SecondTextField;
    private javax.swing.JTextField p8ThirdTextField;
    private javax.swing.JLabel p8TotalLabel;
    private javax.swing.JTextField p9FirstTextField;
    private javax.swing.JTextField p9ForthTextField;
    private javax.swing.JComboBox<String> p9FoulComboBox;
    private javax.swing.JTextField p9SecondTextField;
    private javax.swing.JTextField p9ThirdTextField;
    private javax.swing.JLabel p9TotalLabel;
    private javax.swing.JLabel player10Label;
    private javax.swing.JTextField player10NumberTextField;
    private javax.swing.JLabel player1Label;
    private javax.swing.JTextField player1NumberTextField;
    private javax.swing.JLabel player2Label;
    private javax.swing.JTextField player2NumberTextField;
    private javax.swing.JLabel player3Label;
    private javax.swing.JTextField player3NumberTextField;
    private javax.swing.JLabel player4Label;
    private javax.swing.JTextField player4NumberTextField;
    private javax.swing.JLabel player5Label;
    private javax.swing.JTextField player5NumberTextField;
    private javax.swing.JLabel player6Label;
    private javax.swing.JTextField player6NumberTextField;
    private javax.swing.JLabel player7Label;
    private javax.swing.JTextField player7NumberTextField;
    private javax.swing.JLabel player8Label;
    private javax.swing.JTextField player8NumberTextField;
    private javax.swing.JLabel player9Label;
    private javax.swing.JTextField player9NumberTextField;
    // End of variables declaration//GEN-END:variables
}
