/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JLabel;
import javax.swing.JSeparator;

/**
 *
 * @author rajasharma
 */
public class RecentGame extends javax.swing.JFrame {

    /**
     * Creates new form RecentGame
     */
    public RecentGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numOfFOulsPLabel = new javax.swing.JLabel();
        numOfFOulsALabel = new javax.swing.JLabel();
        numOfPointsP2Label = new javax.swing.JLabel();
        numOfPointsALabel = new javax.swing.JLabel();
        numOfPointsPLabel = new javax.swing.JLabel();
        numOfPointsA2Label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        numOfPointsA3Label = new javax.swing.JLabel();
        numOfPointsP3Label = new javax.swing.JLabel();
        numOfPointsA4Label = new javax.swing.JLabel();
        numOfPointsP4Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Number Of Fouls : ");

        jLabel2.setText("Number Of Points 1st quarter : ");

        jLabel3.setText("Personal");

        jLabel4.setText("Average");

        numOfFOulsPLabel.setText("jLabel6");

        numOfFOulsALabel.setText("jLabel6");

        numOfPointsP2Label.setText("jLabel8");

        numOfPointsALabel.setText("jLabel6");

        numOfPointsPLabel.setText("jLabel8");

        numOfPointsA2Label.setText("jLabel8");

        jLabel6.setText("Number Of Points 2nd quarter : ");

        jLabel7.setText("Number Of Points 3rd quarter : ");

        jLabel8.setText("Number Of Points 4th quarter : ");

        numOfPointsA3Label.setText("jLabel8");

        numOfPointsP3Label.setText("jLabel8");

        numOfPointsA4Label.setText("jLabel8");

        numOfPointsP4Label.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                    .addGap(29, 29, 29))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(numOfPointsPLabel)
                                .addComponent(numOfPointsP2Label)
                                .addComponent(numOfFOulsPLabel)
                                .addComponent(numOfPointsP3Label)
                                .addComponent(numOfPointsP4Label))))
                    .addComponent(jLabel8))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numOfPointsALabel)
                            .addComponent(numOfPointsA2Label)
                            .addComponent(numOfPointsA3Label)
                            .addComponent(numOfPointsA4Label)
                            .addComponent(numOfFOulsALabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numOfFOulsPLabel)
                    .addComponent(numOfFOulsALabel))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(numOfPointsPLabel)
                            .addComponent(numOfPointsALabel))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(numOfPointsP2Label)
                            .addComponent(numOfPointsA2Label))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(numOfPointsP3Label)
                    .addComponent(numOfPointsA3Label))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numOfPointsP4Label)
                    .addComponent(numOfPointsA4Label))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public JSeparator getjSeparator2() {
        return jSeparator2;
    }

    public JSeparator getjSeparator5() {
        return jSeparator5;
    }

    public JLabel getNumOfFOulsALabel() {
        return numOfFOulsALabel;
    }

    public JLabel getNumOfFOulsPLabel() {
        return numOfFOulsPLabel;
    }

    public JLabel getNumOfPointsA2Label() {
        return numOfPointsA2Label;
    }

    public JLabel getNumOfPointsA3Label() {
        return numOfPointsA3Label;
    }

    public JLabel getNumOfPointsA4Label() {
        return numOfPointsA4Label;
    }

    public JLabel getNumOfPointsALabel() {
        return numOfPointsALabel;
    }

    public JLabel getNumOfPointsP2Label() {
        return numOfPointsP2Label;
    }

    public JLabel getNumOfPointsP3Label() {
        return numOfPointsP3Label;
    }

    public JLabel getNumOfPointsP4Label() {
        return numOfPointsP4Label;
    }

    public JLabel getNumOfPointsPLabel() {
        return numOfPointsPLabel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel numOfFOulsALabel;
    private javax.swing.JLabel numOfFOulsPLabel;
    private javax.swing.JLabel numOfPointsA2Label;
    private javax.swing.JLabel numOfPointsA3Label;
    private javax.swing.JLabel numOfPointsA4Label;
    private javax.swing.JLabel numOfPointsALabel;
    private javax.swing.JLabel numOfPointsP2Label;
    private javax.swing.JLabel numOfPointsP3Label;
    private javax.swing.JLabel numOfPointsP4Label;
    private javax.swing.JLabel numOfPointsPLabel;
    // End of variables declaration//GEN-END:variables
}
